29/08/2019 11:17:55 | INFO |app.py | Iniciando aplicação
29/08/2019 11:17:55 | INFO |_internal.py |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
29/08/2019 11:26:35 | INFO |app.py | Iniciando aplicação
29/08/2019 11:26:35 | INFO |_internal.py |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
29/08/2019 11:26:58 | WARNING |auth.py | Falha na autenticação
29/08/2019 11:26:58 | INFO |_internal.py | 127.0.0.1 - - [29/Aug/2019 11:26:58] "POST /sign-in HTTP/1.1" 200 -
29/08/2019 11:27:41 | INFO |auth.py | Usuário logado
29/08/2019 11:27:41 | INFO |_internal.py | 127.0.0.1 - - [29/Aug/2019 11:27:41] "POST /sign-in HTTP/1.1" 200 -
29/08/2019 13:57:45 | INFO |app.py | Iniciando aplicação
29/08/2019 13:57:45 | INFO |_internal.py |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
29/08/2019 14:06:13 | INFO |app.py | Iniciando aplicação
29/08/2019 14:06:13 | INFO |_internal.py |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
29/08/2019 14:06:16 | INFO |_internal.py | 127.0.0.1 - - [29/Aug/2019 14:06:16] "GET /sign-in HTTP/1.1" 200 -
29/08/2019 14:06:16 | INFO |_internal.py | 127.0.0.1 - - [29/Aug/2019 14:06:16] "GET /favicon.ico HTTP/1.1" 404 -
29/08/2019 14:06:25 | INFO |auth.py | Usuário logado
29/08/2019 14:06:25 | INFO |_internal.py | 127.0.0.1 - - [29/Aug/2019 14:06:25] "POST /sign-in HTTP/1.1" 200 -
29/08/2019 14:06:34 | WARNING |auth.py | Falha na autenticação
29/08/2019 14:06:34 | INFO |_internal.py | 127.0.0.1 - - [29/Aug/2019 14:06:34] "POST /sign-in HTTP/1.1" 200 -
29/08/2019 14:14:56 | INFO |app.py | Iniciando aplicação
29/08/2019 14:14:56 | INFO |_internal.py |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
29/08/2019 14:15:02 | INFO |_internal.py | 127.0.0.1 - - [29/Aug/2019 14:15:02] "GET /sign-in HTTP/1.1" 200 -
29/08/2019 14:15:15 | WARNING |auth.py | Falha na autenticação
29/08/2019 14:15:15 | INFO |_internal.py | 127.0.0.1 - - [29/Aug/2019 14:15:15] "POST /sign-in HTTP/1.1" 200 -
